---
title: "WHAM_Run22_2SelBlock_changeESS"
output: html_document
date: '2022-02-27'
---

## Model description
Exactly the same as WHAM run 16, but change catch effective sample size to 30 rather than 100 and survey effective sample size to 30 rather than 50 as was done in ASAP run 12. 

### Load R packages
```{r, echo=FALSE}
library(tidyverse)
library(wham)
library(readxl)
library(DataExplorer)
```

### Load data
```{r}
asap3 <- read_asap3_dat(paste(here::here(), "data", "PlaiceWHAM-2019_revised_NEFSC-LW-WAA_2SelBlock_changeESS.DAT", sep="/"))
```

### Prepare model input
```{r}
# Setup initial selectivity model and parameters
use_n_indices = 2
use_n_selBlocks = 2
modelsetup <- c(rep("logistic", asap3$dat$n_fleet_sel_blocks), rep("age-specific", use_n_indices))

init_fleet_sel <- list(c(2,0.4), c(2,0.4)) # logistic parameters for each selectivity block, based on model type

init_index_sel <- lapply(1:use_n_indices, function(x) c(0.5, 0.5, 0.5, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5))

# Setup fixed parameters
fix_fleet_sel <- lapply(1:(asap3$dat$n_fleets*use_n_selBlocks), function(x) NA) 
# fix_index_sel <- lapply(1:use_n_indices, function(x) 4) # Fix age 4 for both indices,  NA means do not fix 

fix_index_sel[[1]] <- c(4,5) # Fix age 4 & 5 for for index 1
fix_index_sel[[2]][1] <- 4 # Fix age 4 for for index 2

# Setup selectivity list
sel_list <- list(model = modelsetup, # list selectivity model for each fleet and index
                 initial_pars = c(init_fleet_sel, init_index_sel),
                 fix_pars = c(fix_fleet_sel, fix_index_sel))

input <- prepare_wham_input(asap3, selectivity = sel_list, model_name = "WHAM_Run22") 
```

### Fit model, check convergence, and run diagnostics
```{r}
WHAM_Run22 <- fit_wham(input, MakeADFun.silent = TRUE) 
check_convergence(WHAM_Run22)
print(paste("Number of parameters", length(WHAM_Run22$par), sep=" "))

plot_wham_output(mod=WHAM_Run22, out.type='html')
# plot_wham_output(mod=WHAM_Run22, out.type='png', dir.main = paste(here::here(), "WHAM_Run22", sep="/"))
```

### Save input & output
```{r}
# Save model data input
saveRDS(input, file=paste(here::here(), "WG_Revised_Runs", "WHAM_Run22_2SelBlock_changeESS", "WHAM_Run22_input.rds", sep="/"))

# Save fitted model
saveRDS(WHAM_Run22, file=paste(here::here(), "WG_Revised_Runs", "WHAM_Run22_2SelBlock_changeESS", "WHAM_Run22_model.rds", sep="/"))
```

## Comment
AIC is smaller than run 16, but SSB/F/R CV is higher than run 16.

