---
title: "WHAM_Run15_Index2Sel-doublelogistic"
output: html_document
date: '2022-02-25'
---

## Model description
This run is the same as run 14, but changes the selectivity of index 2 (NEFSC fall) to double logistic selectivity.

### Load R packages
```{r, echo=FALSE}
library(tidyverse)
library(wham)
library(readxl)
library(DataExplorer)
```

### Load data
```{r}
asap3 <- read_asap3_dat(paste(here::here(), "data", "PlaiceWHAM-2019_revised_NEFSC-LW-WAA.DAT", sep="/"))
```

### Prepare model input
```{r}
# Setup initial selectivity model and parameters
use_n_indices = 2
modelsetup <- c(rep("logistic", asap3$dat$n_fleet_sel_blocks), c("age-specific", "double-logistic"))

init_fleet_sel <- list(c(2,0.4)) # logistic parameters, based on model type
init_index_sel <- list(c(0.5, 0.5, 0.5, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5), c(2,0.4,2,0.4))

# Setup fixed parameters
fix_fleet_sel <- lapply(1:asap3$dat$n_fleets, function(x) NA)

fix_index_sel <- lapply(1:use_n_indices, function(x) NA) # setup fix selectivity list, NA means do not fix 
fix_index_sel[[1]] <- c(4,5) # Fix age 4 & 5 for for index 1
# fix_index_sel[[2]][1] <- NA # Don't fix any parameters for logistic selectivity

# Setup selectivity list
sel_list <- list(model = modelsetup, # list selectivity model for each fleet and index
                 initial_pars = c(init_fleet_sel, init_index_sel),
                 fix_pars = c(fix_fleet_sel, fix_index_sel))

input <- prepare_wham_input(asap3, selectivity = sel_list, model_name = "WHAM_Run15") 
```

### Fit model, check convergence, and run diagnostics
```{r}
WHAM_Run15 <- fit_wham(input, MakeADFun.silent = TRUE) 
check_convergence(WHAM_Run15)
print(paste("Number of parameters", length(WHAM_Run15$par), sep=" "))

plot_wham_output(mod=WHAM_Run15, out.type='html')
# plot_wham_output(mod=WHAM_Run15, out.type='png', dir.main = paste(here::here(), "WHAM_Run15", sep="/"))
```

### Save input & output
```{r}
# Save model data input
saveRDS(input, file=paste(here::here(), "WG_Revised_Runs", "WHAM_Run15_Index2Sel-doublelogistic", "WHAM_Run15_input.rds", sep="/"))

# Save fitted model
saveRDS(WHAM_Run15, file=paste(here::here(), "WG_Revised_Runs", "WHAM_Run15_Index2Sel-doublelogistic", "WHAM_Run15_model.rds", sep="/"))
```

## Comment


